apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}-{{ .Values.env }}
  labels:
    chart: {{ .Chart.Name }}
    app: {{ .Values.config.name }}
data:
{{- range .Values.config.keyvals }}
{{ . | toYaml | indent 2 }}
{{- end -}}