{{ if .Values.enabled.role }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.role.name }}-{{ .Values.env }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
{{ end }}