{{ if .Values.enabled.secret }}
{{- $passwordValue := (randAlphaNum 16) | b64enc | quote }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}-{{ .Values.env }}
type: Opaque
data:
  username: {{ .Values.secret.username }}
  password: {{ $passwordValue }}
{{ end }}