{{ if .Values.enabled.serviceaccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceaccount.name }}-{{ .Values.env }}
  labels:
    app: {{ .Values.pod.label }}-{{ .Values.env }}
    environment: {{ .Values.env }}
automountServiceAccountToken: false
{{ end }}